export const USERS_FETCH_USERS_LIST_BEGIN = 'USERS_FETCH_USERS_LIST_BEGIN';
export const USERS_FETCH_USERS_LIST_SUCCESS = 'USERS_FETCH_USERS_LIST_SUCCESS';
export const USERS_FETCH_USERS_LIST_FAILURE = 'USERS_FETCH_USERS_LIST_FAILURE';
export const USERS_FETCH_USERS_LIST_DISMISS_ERROR = 'USERS_FETCH_USERS_LIST_DISMISS_ERROR';
